### ISSUE TITLE
Implement Live555 RTSP to my camera

### ISSUE THREAD

**Issue by RS00001** [mpromonet/live555helper#11]
Hello good day!

I've a camera development board which comes with SDK and has provided a sample code that saves stream video (mp4) to a temp directory. I am successfully saving recordings to an NFS share directory and SD card.

Now, I am looking to use an opensource RTSP server to be able to stream those frames over my network. I think Live555 might work but not sure how to as there is no active support or documentation. I'd really appreciate any suggestion or help if you could please provide.

**Comment by mpromonet** [comment]
Hi

This project is an helper to use live555 as a client. For an rtsp server you may look to https://github.com/mpromonet/v4l2rtspserver. It implements an rtsp server  getting frames from v4l2 device.

Best Regards
Michel
