### ISSUE TITLE
I got link error like this

### ISSUE THREAD

**Issue by luowuf** [mpromonet/live555helper#3]
live555helper.a(environment.o):(.rodata._ZTI11Environment[_ZTI11Environment]+0x10): undefined reference to `typeinfo for BasicUsageEnvironment'
live555helper.a(rtspconnectionclient.o):(.rodata._ZTIN14RTSPConnection20RTSPClientConnectionE[_ZTIN14RTSPConnection20RTSPClientConnectionE]+0x10): undefined reference to `typeinfo for RTSPClient'
live555helper.a(SessionSink.o):(.rodata._ZTI11SessionSink[_ZTI11SessionSink]+0x10): undefined reference to `typeinfo for MediaSink'

OS:ubuntu14.04 x86_64
live.2018.04.25

live example is normal,please give me some help，think you!

**Comment by mpromonet** [comment]
Hi,
This is probably because live555 is build with `-fno-rtti` and you are building live555helper without it.
You should either rebuilt live555 without it, or build live555helper with it.
Best Regards,
Michel.
