### ISSUE TITLE
Excuse me, do you have such a problem.

### ISSUE THREAD

**Issue by maiglail** [mpromonet/live555helper#6]
In Android, four cameras are displayed on one page at the same time, sometimes the program crashes.
The log information is as follows:
SIGSEGV(SEGV_MAPERR)
../lib/arm64/libmytechRtspClient.so (MySink::afterGettingFrame(unsigned int, unsigned int, timeval, unsigned int)+1236) [arm64-v8a]
../lib/arm64/libmytechRtspClient.so (MySink::afterGettingFrame(void*, unsigned int, unsigned int, timeval, unsigned int)+120) [arm64-v8a]
../lib/arm64/libmytechRtspClient.so (FramedSource::afterGetting(FramedSource*)+196) [arm64-v8a]
../lib/arm64/libmytechRtspClient.so (MultiFramedRTPSource::doGetNextFrame1()+688) [arm64-v8a]
../lib/arm64/libmytechRtspClient.so (MultiFramedRTPSource::networkReadHandler1()+1328) [arm64-v8a]
../lib/arm64/libmytechRtspClient.so (MultiFramedRTPSource::networkReadHandler(MultiFramedRTPSource*, int)+24) [arm64-v8a]
......
Android will instantiate four fragments in a circular way and display them to the initiating connection camera. I wonder if you have encountered such an exception

**Comment by mpromonet** [comment]
Hi @maiglail,

I guess this depend on code in MySink::afterGettingFrame.
Did you meet the same problem with the library test program `live555helpertest` ?

Best Regards,
Michel.
