### ISSUE TITLE
Live555 Parameters

### ISSUE THREAD

**Issue by drodrig** [mpromonet/live555helper#7]
Hello. Is there any way to pass parameters to the live555 server via the javascript libraries or the config.json file? For instance, I want an RTSP stream to use TCP rather than UDP.

Thank you.

**Comment by mpromonet** [comment]
Hello,

You can ask for an TCP stream creating `RTSPConnection` with rtptransport argument set to  `RTSPConnection::RTPOVERTCP` 

Best Regards,
Michel.
